spring:
  application:
    name: payment-service
  profiles:
    active: none
  config:
    import: optional:configserver:http://52.79.127.196:8071

  cloud:
    config:
      profile: ${PROFILE}

encrypt:
  key: ${ENCRYPT_KEY}
